未完待续

diff --git a/System-Script/app/open b/System-Script/app/open
--- a/System-Script/app/open
+++ b/System-Script/app/open
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-: << !
+: <<!
 Name: open
 Author: YJ
 Email: yj1516268@outlook.com
@@ -20,24 +20,24 @@ Depends:
 ####################################################################
 #------------------------- Program Variable
 # Program name
-name=$(basename "$0")
-readonly name
+NAME=$(basename "${0}")
+readonly NAME
 # Program description
-readonly desc="automatically recognize URL type and open with default program"
-# Program nversion
-readonly major_version=0.4.1
-readonly minor_version=20240704
-readonly rel_version=1
+readonly DESC="automatically recognize URL type and open with default program"
+# Program version
+readonly MAJOR=0.4.1
+readonly MINOR=20240704
+readonly RELEASE=1
 
 #------------------------- Exit Code Variable
-readonly normal=0 # 一切正常
+readonly NORMAL=0 # 一切正常
 
 #------------------------- Other Variable
 # Command
-open="xdg-open"
-editor="nano"
-catimg="feh"
-player="mpv"
+OPEN="xdg-open"
+EDITOR="nano"
+CATIMG="feh"
+PLAYER="mpv"
 # Unable to open file
 declare -a failed_files
 
@@ -47,11 +47,11 @@ declare -a failed_files
 #------------------------- Info Function
 function helpInfo() {
   echo -e ""
-  echo -e "\x1b[32m$name\x1b[0m \x1b[1m$desc\x1b[0m"
+  echo -e "\x1b[32m${NAME}\x1b[0m \x1b[1m${DESC}\x1b[0m"
   echo -e "--------------------------------------------------"
   echo -e "Usage:"
   echo -e ""
-  echo -e "     $name [OPTION]"
+  echo -e "     ${NAME} [OPTION]"
   echo -e ""
   echo -e "Options:"
   echo -e "     -h, --help        Show help information"
@@ -60,42 +60,42 @@ function helpInfo() {
 
 function versionInfo() {
   echo -e ""
-  echo -e "\x1b[1m$name\x1b[0m version (\x1b[1m$major_version-$minor_version.$rel_version\x1b[0m)"
+  echo -e "\x1b[1m${NAME}\x1b[0m version (\x1b[1m${MAJOR}-${MINOR}.${RELEASE}\x1b[0m)"
 }
 
 #------------------------- Feature Function
 function checkCommand() {
   # 确定编辑器
-  if command -v nvim &> /dev/null; then
-    editor="nvim"
-  elif command -v vim &> /dev/null; then
-    editor="vim"
-  elif command -v vi &> /dev/null; then
-    editor="vi"
+  if command -v nvim &>/dev/null; then
+    EDITOR="nvim"
+  elif command -v vim &>/dev/null; then
+    EDITOR="vim"
+  elif command -v vi &>/dev/null; then
+    EDITOR="vi"
   fi
 
   # 确定图片查看器
-  if command -v gwenview &> /dev/null; then # KDE Plasma
-    catimg="gwenview"
-  elif command -v eog &> /dev/null; then # GNOME
-    catimg="eog"
-  elif command -v ristretto &> /dev/null; then # XFCE
-    catimg="ristretto"
-  elif command -v sxiv &> /dev/null; then
-    catimg="sxiv"
-  elif command -v imv &> /dev/null; then
-    catimg="imv"
+  if command -v gwenview &>/dev/null; then # KDE Plasma
+    CATIMG="gwenview"
+  elif command -v eog &>/dev/null; then # GNOME
+    CATIMG="eog"
+  elif command -v ristretto &>/dev/null; then # XFCE
+    CATIMG="ristretto"
+  elif command -v sxiv &>/dev/null; then
+    CATIMG="sxiv"
+  elif command -v imv &>/dev/null; then
+    CATIMG="imv"
   fi
 
   # 确定视频播放器
-  if command -v dragon &> /dev/null; then # KDE Plasma
-    player="dragon"
-  elif command -v totem &> /dev/null; then # GNOME
-    player="totem"
-  elif command -v ristretto &> /dev/null; then # XFCE
-    player="ristretto"
-  elif command -v vlc &> /dev/null; then
-    player="vlc"
+  if command -v dragon &>/dev/null; then # KDE Plasma
+    PLAYER="dragon"
+  elif command -v totem &>/dev/null; then # GNOME
+    PLAYER="totem"
+  elif command -v ristretto &>/dev/null; then # XFCE
+    PLAYER="ristretto"
+  elif command -v vlc &>/dev/null; then
+    PLAYER="vlc"
   fi
 }
 
@@ -103,7 +103,7 @@ function echoFailedFiles() {
   # 输出无法打开的文件的信息
   if [ ${#failed_files[@]} -ne 0 ]; then
     for failed_file in "${failed_files[@]}"; do
-      echo -e "Can not open: $failed_file"
+      echo -e "Can not open: ${failed_file}"
     done
   fi
 }
@@ -116,61 +116,61 @@ function main() {
   local pictures=()
   local videos=()
 
-  for url in "$@"; do
-    if [[ -d $url ]]; then # 文件夹
-      $open "$url" > /dev/null 2>&1
-    elif [[ -f $url ]]; then # 文件
+  for url in "${@}"; do
+    if [[ -d ${url} ]]; then # 文件夹
+      ${OPEN} "${url}" >/dev/null 2>&1
+    elif [[ -f ${url} ]]; then # 文件
       # 判断文件类型
-      file_type=$(file -b --mime-type "$url")
-      if [[ "$file_type" == text/* ]]; then # 普通文本文件
-        texts+=("$url")
-      elif [[ "$file_type" == image/* ]]; then # 图片
-        pictures+=("$url")
-      elif [[ "$file_type" == video/* ]]; then # 视频
-        videos+=("$url")
+      file_type=$(file -b --mime-type "${url}")
+      if [[ "${file_type}" == text/* ]]; then # 普通文本文件
+        texts+=("${url}")
+      elif [[ "${file_type}" == image/* ]]; then # 图片
+        pictures+=("${url}")
+      elif [[ "${file_type}" == video/* ]]; then # 视频
+        videos+=("${url}")
       else
-        $open "$url" > /dev/null 2>&1
+        ${OPEN} "${url}" >/dev/null 2>&1
       fi
-    elif [[ "$url" == file://* ]]; then  # file://*
-      if [[ -d "${url#file://}" ]]; then # 文件夹
-        $open "$url" > /dev/null 2>&1
+    elif [[ "${url}" == file://* ]]; then # file://*
+      if [[ -d "${url#file://}" ]]; then  # 文件夹
+        ${OPEN} "${url}" >/dev/null 2>&1
       elif [[ -f "${url#file://}" ]]; then # 文件
         # 判断文件类型
         file_type=$(file -b --mime-type "${url#file://}")
-        if [[ "$file_type" == text/* ]]; then # 普通文本文件
-          texts+=("$url")
-        elif [[ "$file_type" == image/* ]]; then # 图片
-          pictures+=("$url")
-        elif [[ "$file_type" == video/* ]]; then # 视频
-          videos+=("$url")
+        if [[ "${file_type}" == text/* ]]; then # 普通文本文件
+          texts+=("${url}")
+        elif [[ "${file_type}" == image/* ]]; then # 图片
+          pictures+=("${url}")
+        elif [[ "${file_type}" == video/* ]]; then # 视频
+          videos+=("${url}")
         else
-          $open "$url" > /dev/null 2>&1
+          ${OPEN} "${url}" >/dev/null 2>&1
         fi
       else
         # 将无法打开的文件名添加到数组中
-        failed_files+=("$file")
+        failed_files+=("${file}")
       fi
-    elif [[ "$url" == http://* || "$url" == https://* || "$url" == mailto:* || "$url" == tel:* ]]; then # URL
-      $open "$url" > /dev/null 2>&1
+    elif [[ "${url}" == http://* || "${url}" == https://* || "${url}" == mailto:* || "${url}" == tel:* ]]; then # URL
+      ${OPEN} "${url}" >/dev/null 2>&1
     else
       # 将无法打开的文件名添加到数组中
-      failed_files+=("$file")
+      failed_files+=("${file}")
     fi
   done
 
   # 打开普通文本文件
   if [ ${#texts[@]} -gt 0 ]; then
-    $editor "${texts[@]}"
+    ${EDITOR} "${texts[@]}"
   fi
 
   # 打开图片
   if [ ${#pictures[@]} -gt 0 ]; then
-    $catimg "${pictures[@]}" > /dev/null 2>&1 &
+    ${CATIMG} "${pictures[@]}" >/dev/null 2>&1 &
   fi
 
   # 打开视频
   if [ ${#videos[@]} -gt 0 ]; then
-    $player "${videos[@]}" > /dev/null 2>&1 &
+    ${PLAYER} "${videos[@]}" >/dev/null 2>&1 &
   fi
 
 }
@@ -178,30 +178,30 @@ function main() {
 ####################################################################
 #++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
 ####################################################################
-ARGS=$(getopt --options "hv" --longoptions "help,version" -n "$name" -- "$@")
-eval set -- "$ARGS"
+ARGS=$(getopt --options "hv" --longoptions "help,version" -n "${NAME}" -- "${@}")
+eval set -- "${ARGS}"
 
 if [[ ${#@} -lt 2 ]]; then
-  main "$PWD"
+  main "${PWD}"
 else
   while true; do
-    case $1 in
-      -h | --help)
-        helpInfo
-        exit $normal
-        ;;
-      -v | --version)
-        versionInfo
-        exit $normal
-        ;;
-      --)
-        shift 1
-        ;;
-      *)
-        main "$@"
-        echoFailedFiles
-        exit $normal
-        ;;
+    case ${1} in
+    -h | --help)
+      helpInfo
+      exit ${NORMAL}
+      ;;
+    -v | --version)
+      versionInfo
+      exit ${NORMAL}
+      ;;
+    --)
+      shift 1
+      ;;
+    *)
+      main "${@}"
+      echoFailedFiles
+      exit ${NORMAL}
+      ;;
     esac
   done
 fi
diff --git a/System-Script/app/syncer b/System-Script/app/syncer
--- a/System-Script/app/syncer
+++ b/System-Script/app/syncer
@@ -19,7 +19,20 @@ Depends:
 #+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
 ####################################################################
 #------------------------- Program Variable
-NAME=$(basename "${0}") # 脚本名称
+# Program name
+NAME=$(basename "${0}")
+readonly NAME
+# Program description
+readonly DESC="back up files by system"
+# Program nversion
+readonly MAJOR_VERSION=0.0.3
+readonly MINOR_VERSION=20250812
+readonly RELEASE_VERSION=1
+
+#------------------------- Exit Code Variable
+readonly ERR_FILE=1     # 文件/路径类错误
+readonly ERR_PARAM=2    # 参数错误
+readonly ERR_UKNOWN=255 # 未知错误
 
 #------------------------- Rclone Variable
 TRANSFER=8      # 并行传输任务数
@@ -56,7 +69,42 @@ TARGETS_MUSIC=("CloudMusic" "MyMusic")
 ####################################################################
 #+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
 ####################################################################
+#------------------------- Info Function
+function helpInfo() {
+  echo -e ""
+  echo -e "\x1b[32m${NAME}\x1b[0m \x1b[1m${DESC}\x1b[0m"
+  echo -e "--------------------------------------------------"
+  echo -e "Usage:"
+  echo -e ""
+  echo -e "     ${NAME} [OPTION]"
+  echo -e ""
+  echo -e "Options:"
+  echo -e "     --all            Back up All"
+  echo -e "     --docker         Back up Docker"
+  echo -e "     --music          Back up Music"
+  echo -e ""
+  echo -e "     -h, --help       View this help information"
+  echo -e "     -v, --version    View version information"
+}
+
+function versionInfo() {
+  echo -e ""
+  echo -e "\x1b[1m${NAME}\x1b[0m version (\x1b[1m${MAJOR_VERSION}-${MINOR_VERSION}.${RELEASE_VERSION}\x1b[0m)"
+}
+
 #------------------------- Feature Function
+# 确保指定文件夹存在
+function checkPath() {
+  if [[ -e "${1}" ]]; then
+    if [[ ! -d "${1}" ]]; then
+      echo -e "Path '${1}' is not a folder, exit"
+      exit ${ERR_FILE}
+    fi
+  else
+    mkdir -p "${1}"
+  fi
+}
+
 # 日志函数
 function logger() {
   local line
@@ -77,6 +125,7 @@ function logger() {
   done
 }
 
+# 备份执行器
 function syncer() {
   local storage=${1}
   local storage_type=${2}
@@ -113,7 +162,7 @@ function syncer() {
       fi
     else
       logger "WARN : STORAGE_DEPTH 不是 1 或 2，退出"
-      exit 1
+      exit ${ERR_PARAM}
     fi
 
     logger "INFO  : 正在备份 ${source_path} -> ${storage_path}"
@@ -130,21 +179,56 @@ function syncer() {
     fi
 
     # 检查状态
-    STATUS=${?}
-    if [ ${STATUS} -eq 0 ]; then
+    backup_status=${?}
+    if [ ${backup_status} -eq 0 ]; then
       logger "INFO  : 成功备份 ${source_path}"
     else
-      logger "ERROR : 备份失败 ${source_path}, 错误代码 ${STATUS}"
+      logger "ERROR : 备份失败 ${source_path}, 错误代码 ${backup_status}"
     fi
   done
 }
+
 ####################################################################
 #++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
 ####################################################################
-# 确保日志目录存在
-mkdir -p "${LOGPATH}"
+ARGS=$(getopt --options "hv" --longoptions "help,version" -n "${NAME}" -- "${@}")
+eval set -- "${ARGS}"
 
-# Docker
-syncer "${SYSTEM_STORAGE}" "${SYSTEM_STORAGE_TYPE}" "${SYSTEM_STORAGE_DEPTH}" "${BASE_DOCKER}" "${DIRECTORY_DOCKER}" "${TARGETS_DOCKER[@]}"
-# Music
-syncer "${MUSIC_STORAGE}" "${MUSIC_STORAGE_TYPE}" "${MUSIC_STORAGE_DEPTH}" "${BASE_MUSIC}" "${DIRECTORY_MUSIC}" "${TARGETS_MUSIC[@]}"
+if [[ ${#@} -lt 2 ]]; then
+  helpInfo
+else
+  while true; do
+    checkPath "${LOGPATH}"
+    case ${1} in
+    --all)
+      syncer "${SYSTEM_STORAGE}" "${SYSTEM_STORAGE_TYPE}" "${SYSTEM_STORAGE_DEPTH}" "${BASE_DOCKER}" "${DIRECTORY_DOCKER}" "${TARGETS_DOCKER[@]}"
+      syncer "${MUSIC_STORAGE}" "${MUSIC_STORAGE_TYPE}" "${MUSIC_STORAGE_DEPTH}" "${BASE_MUSIC}" "${DIRECTORY_MUSIC}" "${TARGETS_MUSIC[@]}"
+      shift 1
+      ;;
+    --docker)
+      syncer "${SYSTEM_STORAGE}" "${SYSTEM_STORAGE_TYPE}" "${SYSTEM_STORAGE_DEPTH}" "${BASE_DOCKER}" "${DIRECTORY_DOCKER}" "${TARGETS_DOCKER[@]}"
+      shift 1
+      ;;
+    --music)
+      syncer "${MUSIC_STORAGE}" "${MUSIC_STORAGE_TYPE}" "${MUSIC_STORAGE_DEPTH}" "${BASE_MUSIC}" "${DIRECTORY_MUSIC}" "${TARGETS_MUSIC[@]}"
+      shift 1
+      ;;
+    -h | --help)
+      helpInfo
+      shift 1
+      ;;
+    -v | --version)
+      versionInfo
+      shift 1
+      ;;
+    --)
+      shift 1
+      break
+      ;;
+    *)
+      helpInfo
+      exit ${ERR_UKNOWN}
+      ;;
+    esac
+  done
+fi
