规范化shell脚本

diff --git a/Script/check/check-Arch-pacman_useless_file b/Script/check/check-Arch-pacman_useless_file
--- a/Script/check/check-Arch-pacman_useless_file
+++ b/Script/check/check-Arch-pacman_useless_file
@@ -18,21 +18,81 @@ Depends:
 ####################################################################
 #+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
 ####################################################################
+#------------------------- Program Variable
+# program name
+name=$(basename "$0")
+readonly name
+# program nversion
+readonly major_version=0.0.2
+readonly minor_version=20230213
+readonly rel_version=1
+
+#------------------------- Exit Code Variable
+readonly normal=0        # 一切正常
+readonly err_unknown=255 # 未知错误
+
 #------------------------- Parameter Variable
+# description variable
+readonly desc="用于检测Pacman系统外文件"
+# path variable
 readonly tmp=${TMPDIR-/tmp}/pacman-disowned-$UID-$$
 readonly db=$tmp/db
 readonly fs=$tmp/fs
 
 ####################################################################
+#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
+####################################################################
+#------------------------- Info Function
+function helpInfo() {
+  echo -e ""
+  echo -e "\e[32m$name\e[0m\e[1m$desc\e[0m"
+  echo -e "--------------------------------------------------"
+  echo -e "Usage:"
+  echo -e ""
+  echo -e "     $name OPTIONS"
+  echo -e ""
+  echo -e "Options:"
+  echo -e "     -h, --help            显示帮助信息"
+  echo -e "     -v, --version         显示版本信息"
+}
+
+function versionInfo() {
+  echo -e ""
+  echo -e "\e[1m$name\e[0m version (\e[1m$major_version-$minor_version.$rel_version\e[0m)"
+}
+
+#------------------------- Feature Function
+function main() {
+  mkdir "$tmp"
+  trap 'rm -rf "$tmp"' EXIT
+
+  pacman -Qlq | sort -u > "$db"
+
+  find /bin /etc /lib /sbin /usr \
+    ! -name lost+found \
+    \( -type d -printf '%p/\n' -o -print \) | sort > "$fs"
+
+  comm -23 "$fs" "$db"
+}
+
+####################################################################
 #++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
 ####################################################################
-mkdir "$tmp"
-trap 'rm -rf "$tmp"' EXIT
-
-pacman -Qlq | sort -u > "$db"
-
-find /bin /etc /lib /sbin /usr \
-  ! -name lost+found \
-  \( -type d -printf '%p/\n' -o -print \) | sort > "$fs"
-
-comm -23 "$fs" "$db"
+if [[ ${#@} -lt 1 ]]; then
+  main
+else
+  case $1 in
+    -h | --help)
+      helpInfo
+      exit $normal
+      ;;
+    -v | --version)
+      versionInfo
+      exit $normal
+      ;;
+    *)
+      helpInfo
+      exit $err_unknown
+      ;;
+  esac
+fi
diff --git a/Script/check/check-graphics b/Script/check/check-graphics
--- a/Script/check/check-graphics
+++ b/Script/check/check-graphics
@@ -17,14 +17,78 @@ Depends:
 !
 
 ####################################################################
+#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
+####################################################################
+#------------------------- Program Variable
+# program name
+name=$(basename "$0")
+readonly name
+# program nversion
+readonly major_version=0.0.3
+readonly minor_version=20230213
+readonly rel_version=1
+
+#------------------------- Exit Code Variable
+readonly normal=0        # 一切正常
+readonly err_unknown=255 # 未知错误
+
+#------------------------- Parameter Variable
+# description variable
+readonly desc="用于检测系统显卡信息"
+
+####################################################################
+#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
+####################################################################
+#------------------------- Info Function
+function helpInfo() {
+  echo -e ""
+  echo -e "\e[32m$name\e[0m\e[1m$desc\e[0m"
+  echo -e "--------------------------------------------------"
+  echo -e "Usage:"
+  echo -e ""
+  echo -e "     $name OPTIONS"
+  echo -e ""
+  echo -e "Options:"
+  echo -e "     -h, --help            显示帮助信息"
+  echo -e "     -v, --version         显示版本信息"
+}
+
+function versionInfo() {
+  echo -e ""
+  echo -e "\e[1m$name\e[0m version (\e[1m$major_version-$minor_version.$rel_version\e[0m)"
+}
+
+#------------------------- Feature Function
+function main() {
+  echo -e "\\e[35m显卡信息 ----\\e[0m\n"
+
+  lspci -k | grep --color=auto -A 2 -E "(VGA|3D)"
+
+  echo -e "\n\\e[33m已加载的显卡驱动:\\e[0m"
+  xrandr --listproviders # 系统中已加载的显卡驱动程序
+
+  echo -e "\n\\e[33m默认显卡:\\e[0m"
+  glxinfo | grep "OpenGL renderer" # 查看默认显卡
+}
+
+####################################################################
 #++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
 ####################################################################
-echo -e "\\e[35m显卡信息 ----\\e[0m\n"
-
-lspci -k | grep --color=auto -A 2 -E "(VGA|3D)"
-
-echo -e "\n\\e[33m已加载的显卡驱动:\\e[0m"
-xrandr --listproviders # 系统中已加载的显卡驱动程序
-
-echo -e "\n\\e[33m默认显卡:\\e[0m"
-glxinfo | grep "OpenGL renderer" # 查看默认显卡
+if [[ ${#@} -lt 1 ]]; then
+  main
+else
+  case $1 in
+    -h | --help)
+      helpInfo
+      exit $normal
+      ;;
+    -v | --version)
+      versionInfo
+      exit $normal
+      ;;
+    *)
+      helpInfo
+      exit $err_unknown
+      ;;
+  esac
+fi
diff --git a/Script/wrapper/terminal-time b/Script/wrapper/terminal-time
--- a/Script/wrapper/terminal-time
+++ b/Script/wrapper/terminal-time
@@ -18,17 +18,76 @@ Depends:
 ####################################################################
 #+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
 ####################################################################
+#------------------------- Program Variable
+# program name
+name=$(basename "$0")
+readonly name
+# program nversion
+readonly major_version=0.0.3
+readonly minor_version=20230213
+readonly rel_version=1
+
+#------------------------- Exit Code Variable
+readonly normal=0        # 一切正常
+readonly err_unknown=255 # 未知错误
+
 #------------------------- Parameter Variable
+# description variable
+readonly desc="用于对终端操作进行录制"
 # path variable
 readonly timefile="$HOME/Documents/AppCache/terminal-time/Terminal-Time.time"
 readonly txtfile="$HOME/Documents/AppCache/terminal-time/Terminal-Time.txt"
 
 ####################################################################
+#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
+####################################################################
+#------------------------- Info Function
+function helpInfo() {
+  echo -e ""
+  echo -e "\e[32m$name\e[0m\e[1m$desc\e[0m"
+  echo -e "--------------------------------------------------"
+  echo -e "Usage:"
+  echo -e ""
+  echo -e "     $name OPTIONS"
+  echo -e ""
+  echo -e "Options:"
+  echo -e "     -h, --help            显示帮助信息"
+  echo -e "     -v, --version         显示版本信息"
+}
+
+function versionInfo() {
+  echo -e ""
+  echo -e "\e[1m$name\e[0m version (\e[1m$major_version-$minor_version.$rel_version\e[0m)"
+}
+
+#------------------------- Feature Function
+function main() {
+  ls "$timefile" &> /dev/null && rm "$timefile"
+  ls "$txtfile" &> /dev/null && rm "$txtfile"
+
+  echo -e "\\e[1;34mFlash Start:\\e[0m"
+  script -t -a "$txtfile" 2> "$timefile"
+  echo -e "\n\\e[35mFlash Stop\\e[0m"
+}
+
+####################################################################
 #++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
 ####################################################################
-ls "$timefile" &> /dev/null && rm "$timefile"
-ls "$txtfile" &> /dev/null && rm "$txtfile"
-
-echo -e "\\e[1;34mFlash Start:\\e[0m"
-script -t -a "$txtfile" 2> "$timefile"
-echo -e "\n\\e[35mFlash Stop\\e[0m"
+if [[ ${#@} -lt 1 ]]; then
+  main
+else
+  case $1 in
+    -h | --help)
+      helpInfo
+      exit $normal
+      ;;
+    -v | --version)
+      versionInfo
+      exit $normal
+      ;;
+    *)
+      helpInfo
+      exit $err_unknown
+      ;;
+  esac
+fi
diff --git a/System-Script/app/plasma-script_readupdates b/System-Script/app/plasma-script_readupdates
--- a/System-Script/app/plasma-script_readupdates
+++ b/System-Script/app/plasma-script_readupdates
@@ -15,6 +15,73 @@ Depends:
 -
 !
 
-if [ -f /tmp/polybar-script_checkupdates.log ]; then
-  cat /tmp/polybar-script_checkupdates.log
+####################################################################
+#+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
+####################################################################
+#------------------------- Program Variable
+# program name
+name=$(basename "$0")
+readonly name
+# program nversion
+readonly major_version=0.0.3
+readonly minor_version=20230213
+readonly rel_version=1
+
+#------------------------- Exit Code Variable
+readonly normal=0        # 一切正常
+readonly err_unknown=255 # 未知错误
+
+#------------------------- Parameter Variable
+# description variable
+readonly desc="用于读取系统更新信息"
+
+####################################################################
+#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
+####################################################################
+#------------------------- Info Function
+function helpInfo() {
+  echo -e ""
+  echo -e "\e[32m$name\e[0m\e[1m$desc\e[0m"
+  echo -e "--------------------------------------------------"
+  echo -e "Usage:"
+  echo -e ""
+  echo -e "     $name OPTIONS"
+  echo -e ""
+  echo -e "Options:"
+  echo -e "     -h, --help            显示帮助信息"
+  echo -e "     -v, --version         显示版本信息"
+}
+
+function versionInfo() {
+  echo -e ""
+  echo -e "\e[1m$name\e[0m version (\e[1m$major_version-$minor_version.$rel_version\e[0m)"
+}
+
+#------------------------- Feature Function
+function main() {
+  if [ -f /tmp/polybar-script_checkupdates.log ]; then
+    cat /tmp/polybar-script_checkupdates.log
+  fi
+}
+
+####################################################################
+#++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
+####################################################################
+if [[ ${#@} -lt 1 ]]; then
+  main
+else
+  case $1 in
+    -h | --help)
+      helpInfo
+      exit $normal
+      ;;
+    -v | --version)
+      versionInfo
+      exit $normal
+      ;;
+    *)
+      helpInfo
+      exit $err_unknown
+      ;;
+  esac
 fi
diff --git a/System-Script/app/polybar-script_redshift-info b/System-Script/app/polybar-script_redshift-info
--- a/System-Script/app/polybar-script_redshift-info
+++ b/System-Script/app/polybar-script_redshift-info
@@ -18,7 +18,22 @@ Depends:
 ####################################################################
 #+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
 ####################################################################
+#------------------------- Program Variable
+# program name
+name=$(basename "$0")
+readonly name
+# program version
+readonly major_version=2.1.2
+readonly minor_version=20230213
+readonly rel_version=1
+
+#------------------------- Exit Code Variable
+readonly normal=0        # 一切正常
+readonly err_unknown=255 # 未知错误
+
 #------------------------- Parameter Variable
+# description variable
+readonly desc="是Polybar的脚本，用于获取色温信息"
 # language variable
 if [[ $LANG == 'zh_CN.UTF-8' ]]; then
   color_temp='色温'
@@ -27,18 +42,65 @@ else
 fi
 
 ####################################################################
+#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
+####################################################################
+#------------------------- Info Function
+function helpInfo() {
+  echo -e ""
+  echo -e "\e[32m$name\e[0m\e[1m$desc\e[0m"
+  echo -e "--------------------------------------------------"
+  echo -e "Usage:"
+  echo -e ""
+  echo -e "     $name [OPTION]"
+  echo -e ""
+  echo -e "Options:"
+  echo -e "     -c, --check       检测软件包更新"
+  echo -e "     -e, --empty       清空tmp文件内容"
+  echo -e ""
+  echo -e "     -h, --help        显示帮助信息"
+  echo -e "     -v, --version     显示版本信息"
+}
+
+function versionInfo() {
+  echo -e ""
+  echo -e "\e[1m$name\e[0m version (\e[1m$major_version-$minor_version.$rel_version\e[0m)"
+}
+
+#------------------------- Feature Function
+function main() {
+  if [ "$(pgrep -x redshift)" ]; then
+    temp=$(redshift -p 2> /dev/null | grep "$color_temp" | cut -d ":" -f 2 | tr -dc "[:digit:]")
+
+    if [ -z "$temp" ]; then
+      echo "%{F#65737E}"
+    elif [ "$temp" -ge 5000 ]; then
+      echo "%{F#8FA1B3}"
+    elif [ "$temp" -ge 4000 ]; then
+      echo "%{F#EBCB8B}"
+    else
+      echo "%{F#D08770}"
+    fi
+  fi
+}
+
+####################################################################
 #++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
 ####################################################################
-if [ "$(pgrep -x redshift)" ]; then
-  temp=$(redshift -p 2> /dev/null | grep "$color_temp" | cut -d ":" -f 2 | tr -dc "[:digit:]")
-
-  if [ -z "$temp" ]; then
-    echo "%{F#65737E}"
-  elif [ "$temp" -ge 5000 ]; then
-    echo "%{F#8FA1B3}"
-  elif [ "$temp" -ge 4000 ]; then
-    echo "%{F#EBCB8B}"
-  else
-    echo "%{F#D08770}"
-  fi
+if [[ ${#@} -lt 1 ]]; then
+  main
+else
+  case $1 in
+    -h | --help)
+      helpInfo
+      exit $normal
+      ;;
+    -v | --version)
+      versionInfo
+      exit $normal
+      ;;
+    *)
+      helpInfo
+      exit $err_unknown
+      ;;
+  esac
 fi
diff --git a/System-Script/app/rolling-count b/System-Script/app/rolling-count
--- a/System-Script/app/rolling-count
+++ b/System-Script/app/rolling-count
@@ -18,7 +18,22 @@ Depends:
 ####################################################################
 #+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
 ####################################################################
+#------------------------- Program Variable
+# program name
+name=$(basename "$0")
+readonly name
+# program nversion
+readonly major_version=0.0.3
+readonly minor_version=20230213
+readonly rel_version=1
+
+#------------------------- Exit Code Variable
+readonly normal=0        # 一切正常
+readonly err_unknown=255 # 未知错误
+
 #------------------------- Parameter Variable
+# description variable
+readonly desc="用于统计系统安装和更新信息"
 # statistics variable
 installation_time=$(head -n1 /var/log/pacman.log | cut -d " " -f 1,2)
 readonly installation_time # 系统安装时间
@@ -28,13 +43,11 @@ installation_date=$(echo "$installation_time" | cut -d " " -f 1 | sed 's/[][]//g
 readonly installation_date # 系统安装日期
 days=$((($(date +%s) - $(date +%s -d "$installation_date")) / 86400))
 readonly days # 系统安装天数
-
 ## System upgrade
 system_update_count=$(grep -c "starting full system upgrade" /var/log/pacman.log)
 readonly system_update_count # 系统更新计次数
 system_update_mean=$(awk 'BEGIN{printf "%.2f",'"$system_update_count"'/'"$days"'}')
 readonly system_update_mean # 系统更新频率
-
 ## Kernel update
 kernel_update_count=$(grep -c "upgraded linux " /var/log/pacman.log)
 readonly kernel_update_count # 内核更新次数
@@ -47,13 +60,57 @@ latest_kernel_version=$(uname -r)
 readonly latest_kernel_version # 最近安装的内核版本
 
 ####################################################################
+#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
+####################################################################
+#------------------------- Info Function
+function helpInfo() {
+  echo -e ""
+  echo -e "\e[32m$name\e[0m\e[1m$desc\e[0m"
+  echo -e "--------------------------------------------------"
+  echo -e "Usage:"
+  echo -e ""
+  echo -e "     $name OPTIONS"
+  echo -e ""
+  echo -e "Options:"
+  echo -e "     -h, --help            显示帮助信息"
+  echo -e "     -v, --version         显示版本信息"
+}
+
+function versionInfo() {
+  echo -e ""
+  echo -e "\e[1m$name\e[0m version (\e[1m$major_version-$minor_version.$rel_version\e[0m)"
+}
+
+#------------------------- Feature Function
+function main() {
+  printf "\\e[36m%18s\\e[0m %-2s \\e[36m%-18s\\e[0m\n" "$installation_time" "--" "[$now_time]"
+  printf "\\e[35m%18s\\e[0m %-2s \\e[35m%-18s\\e[0m\n" "$oldest_kernel_version" "--" "$latest_kernel_version"
+  printf "%24s %-2s \\e[37m%-10s\\e[0m\n" "系统使用时长" "--" "$days 天"
+  printf "%24s %-2s \\e[37m%-10s\\e[0m\n" "系统更新次数" "--" "$system_update_count 次"
+  printf "%24s %-2s \\e[37m%-10s\\e[0m\n" "系统更新频率" "--" "$system_update_mean 次/天"
+  printf "%24s %-2s \\e[37m%-10s\\e[0m\n" "内核更新次数" "--" "$kernel_update_count 次"
+  printf "%24s %-2s \\e[37m%-10s\\e[0m\n" "内核更新频率" "--" "$kernel_update_mean 天/次"
+  repo-elephant
+}
+
+####################################################################
 #++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
 ####################################################################
-printf "\\e[36m%18s\\e[0m %-2s \\e[36m%-18s\\e[0m\n" "$installation_time" "--" "[$now_time]"
-printf "\\e[35m%18s\\e[0m %-2s \\e[35m%-18s\\e[0m\n" "$oldest_kernel_version" "--" "$latest_kernel_version"
-printf "%24s %-2s \\e[37m%-10s\\e[0m\n" "系统使用时长" "--" "$days 天"
-printf "%24s %-2s \\e[37m%-10s\\e[0m\n" "系统更新次数" "--" "$system_update_count 次"
-printf "%24s %-2s \\e[37m%-10s\\e[0m\n" "系统更新频率" "--" "$system_update_mean 次/天"
-printf "%24s %-2s \\e[37m%-10s\\e[0m\n" "内核更新次数" "--" "$kernel_update_count 次"
-printf "%24s %-2s \\e[37m%-10s\\e[0m\n" "内核更新频率" "--" "$kernel_update_mean 天/次"
-repo-elephant
+if [[ ${#@} -lt 1 ]]; then
+  main
+else
+  case $1 in
+    -h | --help)
+      helpInfo
+      exit $normal
+      ;;
+    -v | --version)
+      versionInfo
+      exit $normal
+      ;;
+    *)
+      helpInfo
+      exit $err_unknown
+      ;;
+  esac
+fi
diff --git a/System-Script/app/scleaner b/System-Script/app/scleaner
--- a/System-Script/app/scleaner
+++ b/System-Script/app/scleaner
@@ -18,17 +18,76 @@ Depends:
 ####################################################################
 #+++++++++++++++++++++++++ Define Variable ++++++++++++++++++++++++#
 ####################################################################
+#------------------------- Program Variable
+# program name
+name=$(basename "$0")
+readonly name
+# program nversion
+readonly major_version=0.0.3
+readonly minor_version=20230213
+readonly rel_version=1
+
+#------------------------- Exit Code Variable
+readonly normal=0        # 一切正常
+readonly err_unknown=255 # 未知错误
+
 #------------------------- Parameter Variable
+# description variable
+readonly desc="用于卸载孤立包"
 # detection variable
 lonely_pkgs=$(pacman -Qtdq)
 readonly lonely_pkgs
 
 ####################################################################
+#+++++++++++++++++++++++++ Define Function ++++++++++++++++++++++++#
+####################################################################
+#------------------------- Info Function
+function helpInfo() {
+  echo -e ""
+  echo -e "\e[32m$name\e[0m\e[1m$desc\e[0m"
+  echo -e "--------------------------------------------------"
+  echo -e "Usage:"
+  echo -e ""
+  echo -e "     $name OPTIONS"
+  echo -e ""
+  echo -e "Options:"
+  echo -e "     -h, --help            显示帮助信息"
+  echo -e "     -v, --version         显示版本信息"
+}
+
+function versionInfo() {
+  echo -e ""
+  echo -e "\e[1m$name\e[0m version (\e[1m$major_version-$minor_version.$rel_version\e[0m)"
+}
+
+#------------------------- Feature Function
+function main() {
+  if [[ -z $lonely_pkgs ]]; then
+    echo -e "\\e[35m[✔]\\e[0m 没有需要清理的包"
+    repo-elephant
+  else
+    pacman -Rn $lonely_pkgs # 不能使用引号
+  fi
+}
+
+####################################################################
 #++++++++++++++++++++++++++++++ Main ++++++++++++++++++++++++++++++#
 ####################################################################
-if [[ -z $lonely_pkgs ]]; then
-  echo -e "\\e[35m[✔]\\e[0m 没有需要清理的包"
-  repo-elephant
+if [[ ${#@} -lt 1 ]]; then
+  main
 else
-  pacman -Rn $lonely_pkgs # 不能使用引号
+  case $1 in
+    -h | --help)
+      helpInfo
+      exit $normal
+      ;;
+    -v | --version)
+      versionInfo
+      exit $normal
+      ;;
+    *)
+      helpInfo
+      exit $err_unknown
+      ;;
+  esac
 fi
